{{- include "sch.config.init" (list . "ibm-sccm.sch.chart.config.values") }}
{{ $appName := include "sch.names.appName" (list .) }}
{{ $fullName := include "sch.names.fullName" (list .) }}
{{ $saName := include "sch.names.fullCompName" (list . "serviceaccount") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{  $fullName  }}-prerollback
  labels:
    app.kubernetes.io/name: {{  $appName  }}
    app.kubernetes.io/instance: {{  .Release.Name  }}
    app.kubernetes.io/managed-by: {{  .Release.Service  }}
    helm.sh/chart: {{  include "ibm-sccm.chart" .  }}
    release: {{  .Release.Name  }}
  annotations:
    "helm.sh/hook": pre-rollback
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/name: {{  $appName  }}-prerollback
        app.kubernetes.io/instance: {{  .Release.Name  }}-prerollback
        app.kubernetes.io/managed-by: {{  .Release.Service  }}-prerollback
        helm.sh/chart: {{  include "ibm-sccm.chart" .  }}-prerollback
        release: {{  .Release.Name  }}-prerollback
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering "" "" nil) | indent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ $saName }}
      {{- else }}
      serviceAccountName: {{ .Values.serviceAccount.name | default "default" }}
      {{- end }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
{{ include "sch.security.securityContext" (list . .sch.chart.podSecurityContext) | indent 8 }}
      affinity:
{{- include "ibm-sccm.nodeAffinity" (list . .Values.affinity.nodeAffinity) | indent 8 }}
{{- include "ibm-sccm.podAffinity" (list . .Values.affinity.podAffinity) | indent 8 }}
{{- include "ibm-sccm.podAntiAffinity" (list . .Values.affinity.podAntiAffinity) | indent 8 }}
      restartPolicy: Never
      containers:
        - name: post-rollback-job
          {{- if .Values.image.digest.enabled }}
          image: "{{  .Values.image.repository  }}@{{ .Values.image.digest.value }}"
          {{- else }}
          image: "{{  .Values.image.repository  }}:{{ .Values.image.tag  }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/maintenance.sh", "rollback", {{  .Release.Name  }}-{{  $appName  }}]
          volumeMounts:
            - mountPath: /app/backup
              name: cc-volume 
          resources:
            limits:
{{ toYaml .Values.initResources.limits | indent 14 }}
            requests:
{{ toYaml .Values.initResources.requests | indent 14 }}
          securityContext:
{{ include "sch.security.securityContext" (list . .sch.chart.containerSecurityContext) | indent 12 }}
      volumes:
      - name: cc-volume
        persistentVolumeClaim:
          {{- if .Values.persistentVolumeCCM.claimName}}
          claimName: {{ .Values.persistentVolumeCCM.claimName}}
          {{- else }}
          claimName: {{  $fullName  }}-pvc-ccm
          {{- end }}
