{{- include "sch.config.init" (list . "ibm-sccm.sch.chart.config.values") }}
{{ $fullName := include "sch.names.fullName" (list .) }}
{{ $appName := include "sch.names.appName" (list .) }}
{{- if .Values.route.enabled }}
{{- if (.Capabilities.APIVersions.Has "route.openshift.io/v1") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{  $appName  }}
    app.kubernetes.io/instance: {{  .Release.Name  }}
    app.kubernetes.io/managed-by: {{  .Release.Service  }}
    helm.sh/chart: {{  include "ibm-sccm.chart" .  }}
    release: {{  .Release.Name  }}
spec:
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 50
  port:
    targetPort: web-console-secure
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
{{- end }}
{{- end }}