{
 "title": "ibm-ssp-cm",
 "description": "Cluster monitoring dashboard for IBM Sterling Control Center Monitor",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "query": ".*" },
   { "name": "namespace", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Pod Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable_pods{node=~\".*\"})"
      }
     ]
    },
    {
     "title": "Cluster CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Cluster Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Cluster Disk Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (node_filesystem_size{nodename=~\"$node\"}) - sum (node_filesystem_free{nodename=~\"$node\"})) / sum (node_filesystem_size{nodename=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Cluster Pod Capacity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "pods" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable_pods{node=~\"$node\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(kube_pod_info{node=~\"$node\"})",
       "legendFormat": "requested"
      }
     ]
    },
    {
     "title": "Cluster CPU Capacity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity_cpu_cores{node=~\"$node\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"})",
       "legendFormat": "requested"
      }
     ]
    },
    {
     "title": "Cluster Mem Capacity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"$node\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"})",
       "legendFormat": "requested"
      }
     ]
    },
    {
     "title": "Cluster Disk Capacity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_filesystem_size{nodename=~\"$node\"}) - sum(node_filesystem_free{nodename=~\"$node\"})",
       "legendFormat": "usage"
      },
      {
       "expr": "sum(node_filesystem_size{nodename=~\"$node\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Nodes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_node_info{node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Nodes Out of Disk",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$node\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes Unavailable",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Running",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Pending",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
      }
     ]
    },
    {
     "title": "Pods Failed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
      }
     ]
    },
    {
     "title": "Pods Succeeded",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
      }
     ]
    },
    {
     "title": "Pods Unknown",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Running",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Waiting",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Terminated",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Restarts (Last 30 Minutes)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(delta(kube_pod_container_status_restarts{namespace=\"kube-system\"}[30m]))"
      }
     ]
    },
    {
     "title": "CPU Cores Requested by Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Memory Requested By Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", node=~\"$node\"})"
      }
     ]
    }
   ]
  }
 ]
}